const groups={new:'Новинки',emotion:'ROYCE EMOTIONAL',sense:'ROYCE SENSE',enjoy:'ROYCE ENJOY'};
const form=document.querySelector('[data-product-form]');
const tableBody=document.querySelector('[data-products-table]');
const formTitle=document.querySelector('[data-form-title]');
const submitButton=document.querySelector('[data-submit-button]');
const cancelButton=document.querySelector('[data-cancel-edit]');
const resetButton=document.querySelector('[data-reset-products]');
const filterButtons=document.querySelectorAll('[data-filter]');
let currentFilter='all';

function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[char]))}
function readFileAsDataUrl(file){return new Promise(resolve=>{if(!file){resolve('');return}const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>resolve('');reader.readAsDataURL(file)})}
function getProducts(){return QVProducts.getAll().sort((a,b)=>(Number(a.sortOrder)||0)-(Number(b.sortOrder)||0)||Number(a.id)-Number(b.id))}
function saveProducts(products){QVProducts.saveAll(products)}
function resetForm(){form.reset();form.elements.id.value='';form.elements.unit.value='м²';form.elements.sortOrder.value='0';form.elements.isActive.checked=true;formTitle.textContent='Добавить товар';submitButton.textContent='Добавить товар';cancelButton.hidden=true}
function renderTable(){const products=getProducts().filter(product=>currentFilter==='all'||product.group===currentFilter);if(!products.length){tableBody.innerHTML='<tr><td colspan="10">Товары не найдены</td></tr>';return}tableBody.innerHTML=products.map(product=>`<tr><td>${product.id}</td><td><img class="table-img" src="${QVProducts.adminImageSrc(product.image)}" alt=""></td><td>${escapeHtml(groups[product.group]||product.group)}</td><td><strong>${escapeHtml(product.title)}</strong><span>${escapeHtml(product.meta)}</span></td><td>${QVProducts.formatPrice(product.price)} / ${escapeHtml(product.unit||'м²')}</td><td>${product.oldPrice?QVProducts.formatPrice(product.oldPrice):'—'}</td><td>${new Date(product.createdAt).toLocaleDateString('ru-RU')}</td><td>${product.isActive?'Показывается':'Скрыт'}</td><td>${product.sortOrder||0}</td><td><div class="row-actions"><button type="button" data-edit="${product.id}">Изменить</button><button type="button" class="delete" data-delete="${product.id}">Удалить</button></div></td></tr>`).join('')}
async function handleSubmit(event){event.preventDefault();const data=new FormData(form);const id=Number(data.get('id'))||0;let products=getProducts();const imageFile=form.elements.imageFile.files[0];const hoverFile=form.elements.imageHoverFile.files[0];const imageData=await readFileAsDataUrl(imageFile);const hoverData=await readFileAsDataUrl(hoverFile);const current=id?products.find(product=>product.id===id):null;const product={id:id||QVProducts.getNextId(),group:data.get('group')||'new',title:String(data.get('title')||'').trim(),meta:String(data.get('meta')||'').trim(),price:Number(data.get('price'))||0,oldPrice:data.get('oldPrice')===''?'':Number(data.get('oldPrice'))||'',unit:String(data.get('unit')||'м²').trim(),image:imageData||String(data.get('image')||'').trim()||(current?current.image:'new-light.png'),imageHover:hoverData||String(data.get('imageHover')||'').trim()||(current?current.imageHover:''),createdAt:current?current.createdAt:new Date().toISOString(),isActive:form.elements.isActive.checked,sortOrder:Number(data.get('sortOrder'))||0};if(!product.imageHover)product.imageHover=product.image;if(!product.title||!product.meta||!product.price){alert('Заполните название, характеристики и цену.');return}if(id){products=products.map(item=>item.id===id?product:item)}else{products.push(product)}saveProducts(products);resetForm();renderTable();alert(id?'Товар изменен.':'Товар добавлен.')}
function editProduct(id){const product=getProducts().find(item=>item.id===id);if(!product)return;form.elements.id.value=product.id;form.elements.group.value=product.group;form.elements.title.value=product.title;form.elements.meta.value=product.meta;form.elements.price.value=product.price;form.elements.oldPrice.value=product.oldPrice||'';form.elements.unit.value=product.unit||'м²';form.elements.image.value=product.image&&product.image.startsWith('data:')?'':product.image;form.elements.imageHover.value=product.imageHover&&product.imageHover.startsWith('data:')?'':product.imageHover;form.elements.sortOrder.value=product.sortOrder||0;form.elements.isActive.checked=product.isActive!==false;form.elements.imageFile.value='';form.elements.imageHoverFile.value='';formTitle.textContent='Редактировать товар';submitButton.textContent='Сохранить изменения';cancelButton.hidden=false;window.scrollTo({top:0,behavior:'smooth'})}
function deleteProduct(id){if(!confirm('Удалить товар?'))return;const products=getProducts().filter(product=>product.id!==id);saveProducts(products);renderTable();if(Number(form.elements.id.value)===id)resetForm()}
form.addEventListener('submit',handleSubmit);cancelButton.addEventListener('click',resetForm);tableBody.addEventListener('click',event=>{const edit=event.target.closest('[data-edit]');const del=event.target.closest('[data-delete]');if(edit)editProduct(Number(edit.dataset.edit));if(del)deleteProduct(Number(del.dataset.delete))});filterButtons.forEach(button=>{button.addEventListener('click',()=>{filterButtons.forEach(item=>item.classList.remove('active'));button.classList.add('active');currentFilter=button.dataset.filter;renderTable()})});resetButton.addEventListener('click',()=>{if(!confirm('Сбросить товары к начальному состоянию? Все изменения localStorage будут удалены.'))return;QVProducts.reset();resetForm();renderTable()});renderTable();
